name: chatscreen
description: An easy way to add chat to your project
version: 0.0.1+2
homepage: https://github.com/GursheeshSingh/chat_screen_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pull_to_refresh: ^1.5.8
  shimmer: ^1.1.0
  flutter_icons: ^1.0.0+1
  video_thumbnail: ^0.2.0
  permission_handler: ^5.0.0+hotfix.3
  image_picker: ^0.6.4

  cached_network_image: ^2.1.0+1
  photo_view: ^0.9.1
  video_player: ^0.10.8+1
  uuid: ^2.0.4
  parse_server_sdk: ^1.0.26

  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  firebase_database: ^3.1.5
  firebase_storage: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:
    - family: Acumin
      fonts:
        - asset: fonts/ttcommons_regular.ttf