name: chatscreen
description: An easy way to add chat to your project
version: 0.0.2+3
homepage: https://github.com/GursheeshSingh/chat_screen_flutter

environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  pull_to_refresh:
  shimmer:
  flutter_icons:
  video_thumbnail:
  permission_handler:
  image_picker:
  bubble:
  intl:

  cached_network_image:
  photo_view:
  video_player:
  uuid:
  parse_server_sdk:

  firebase_core:
  cloud_firestore:
  firebase_database:
  firebase_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:
    - family: Acumin
      fonts:
        - asset: fonts/ttcommons_regular.ttf